# Generated by Django 5.2.4 on 2025-07-21 15:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('viewed', 'Viewed'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'job_applications',
                'indexes': [models.Index(fields=['job_id', 'status'], name='job_applica_job_id_e29281_idx'), models.Index(fields=['user_id', 'status'], name='job_applica_user_id_8bc527_idx'), models.Index(fields=['applied_at'], name='job_applica_applied_5065c0_idx')],
                'unique_together': {('job_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='JobBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'job_bookmarks',
                'indexes': [models.Index(fields=['job_id', 'user_id'], name='job_bookmar_job_id_88168a_idx'), models.Index(fields=['bookmarked_at'], name='job_bookmar_bookmar_238560_idx')],
                'unique_together': {('job_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('filters', models.JSONField(default=dict)),
                ('results_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'job_searches',
                'indexes': [models.Index(fields=['user_id', 'searched_at'], name='job_searche_user_id_21a3f6_idx'), models.Index(fields=['query'], name='job_searche_query_19e2ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'job_views',
                'indexes': [models.Index(fields=['job_id', 'viewed_at'], name='job_views_job_id_994b7a_idx'), models.Index(fields=['user_id', 'viewed_at'], name='job_views_user_id_2dd5a6_idx')],
            },
        ),
    ]
