# Generated by Django 5.2.4 on 2025-07-20 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_premium_apikey_apirequestlog_securityevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_type', models.CharField(choices=[('profile', 'Profile Photo'), ('cover', 'Cover Photo'), ('gallery', 'Gallery Photo')], default='profile', max_length=20)),
                ('image', models.ImageField(upload_to='user_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary photo for this type')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type of the image', max_length=50)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'photo_type'], name='accounts_us_user_id_a7e8f1_idx'), models.Index(fields=['is_primary'], name='accounts_us_is_prim_aa5a7e_idx'), models.Index(fields=['uploaded_at'], name='accounts_us_uploade_210029_idx')],
                'unique_together': {('user', 'photo_type', 'is_primary')},
            },
        ),
    ]
