# Generated by Django 5.2.4 on 2025-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_display',
            field=models.CharField(blank=True, help_text='Original salary text', max_length=255, null=True),
        ),
    ]
