# Generated by Django 5.2.4 on 2025-07-21 15:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('job_view', 'Job View'), ('job_apply', 'Job Application'), ('job_bookmark', 'Job Bookmark'), ('search', 'Search'), ('filter', 'Filter'), ('user_signup', 'User Signup'), ('user_login', 'User Login'), ('page_view', 'Page View')], db_index=True, max_length=20)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('event_data', models.JSONField(default=dict)),
                ('page_url', models.URLField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'analytics_events',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_c3dcde_idx'), models.Index(fields=['user_id', 'created_at'], name='analytics_e_user_id_7e4ee5_idx'), models.Index(fields=['session_id', 'created_at'], name='analytics_e_session_283fe0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_jobs', models.IntegerField(default=0)),
                ('new_jobs', models.IntegerField(default=0)),
                ('active_jobs', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('new_applications', models.IntegerField(default=0)),
                ('job_views', models.IntegerField(default=0)),
                ('job_bookmarks', models.IntegerField(default=0)),
                ('searches', models.IntegerField(default=0)),
                ('top_keywords', models.JSONField(default=list)),
                ('top_locations', models.JSONField(default=list)),
                ('top_companies', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_metrics',
                'indexes': [models.Index(fields=['date'], name='daily_metri_date_07dd2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('search_count', models.IntegerField(default=0)),
                ('results_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_analytics',
                'indexes': [models.Index(fields=['query', 'date'], name='search_anal_query_81ad52_idx')],
                'unique_together': {('query', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('job_views', models.IntegerField(default=0)),
                ('job_applications', models.IntegerField(default=0)),
                ('job_bookmarks', models.IntegerField(default=0)),
                ('searches', models.IntegerField(default=0)),
                ('sessions_count', models.IntegerField(default=0)),
                ('total_session_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_activity',
                'indexes': [models.Index(fields=['user_id', 'date'], name='user_activi_user_id_ecf6ce_idx')],
                'unique_together': {('user_id', 'date')},
            },
        ),
    ]
